services:
  postgres:
    image: postgres:alpine  
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  auth_service:
    image: auth_service
    build:
      context: ./auth
    ports:
      - "8080:8080"
    depends_on:
      user_service:
        condition: service_started
  
  task_service:
    image: task_service
    build:
      context: ./task
    ports:
      - "8081:8081"
    depends_on:
      user_service:
        condition: service_started
    
  user_service:
    image: user_service
    build:
      context: ./user
    ports:
      - "443:443"
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    
volumes:
  postgres-data: