global:
  resolve_timeout: 5m

route:
  receiver: telegram_receiver
  group_by: ["alertname", "Host"]
  group_wait: 1s
  group_interval: 1s
  repeat_interval: 24h

  routes:
  - receiver: 'telegram_receiver'
    matchers:
    - severity="Critical"

receivers:
- name: 'telegram_receiver'
  telegram_configs:
  - api_url: 'https://api.telegram.org'
    send_resolved: true
    bot_token: 8034616958:AAFFacxq3nHviDbMaXHBjwLXTPxbn2CZKnU
    chat_id: 824644156
    message: |
      🚨 ALERT: {{ .GroupLabels.alertname }}
      Status: {{ .Status }}
      {{ range .Alerts }}
      Instance: {{ .Labels.instance }}
      Summary: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      {{ end }}
    parse_mode: 'HTML'
